name: kingz_cut_mobile
description: "Mobile app for Kingz Cut salon shop used by Barbers and customers."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  dartx: ^1.2.0
  dio: 5.7.0
  jiffy: ^6.4.3
  google_fonts: 6.2.1
  flutter_native_splash: 2.4.2
  flex_color_scheme: ^8.2.0
  logger: 2.4.0
  go_router: 14.3.0
  introduction_screen: ^3.1.11
  dropdown_button2: 2.3.9
  uiblock: 2.0.3
  flutter_secure_storage: 9.2.2
  shimmer: 3.0.0
  cached_network_image: 3.4.1
  readmore: 3.0.0
  mime: 2.0.0
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.2.0
  intl: ^0.20.2
  email_validator: ^3.0.0
  email_otp: ^3.0.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_database: ^11.3.6
  google_sign_in: ^6.3.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  # flutter_launcher_icons: 0.13.1
  flutter_launcher_icons: ^0.14.3
  json_serializable: 6.8.0
  rename: ^3.0.2
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  freezed: ^2.4.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/services/
    - assets/images/icons/
    - assets/images/hairstyles/
    - assets/images/stylists/
